### ISSUE TITLE
Add support for localization

### ISSUE THREAD

**Issue by jens1o** [cg-cnu/vscode-remind-me#1]
Personally, I'd like to provide German translation :)

It's a very cool extension, thanks!

**Comment by cg-cnu** [comment]
@jens1o You are most welcome to do a pr 💯  Cheers!

**Comment by jens1o** [comment]
How do you expect the file structure to be?

**Comment by cg-cnu** [comment]
I haven't done any translation stuff so, not exactly sure. Feel free to take a call 🙂

**Comment by jens1o** [comment]
I'm going to do that as soon as I've got more time.

**Comment by KobayashiRo** [comment]
may be you can add keyword like at .
e.g  watch tv at 22:00
and it will remind me at 22:00

**Comment by cg-cnu** [comment]
@KobayashiRo Interesting suggestion. created a new issue. Lets talk over there...

**Comment by cg-cnu** [comment]
Hi @jens1o ! I am closing this issue for now. If you still feel like you can add the PR feel free to create a new issue. Thanks!
