### ISSUE TITLE
remind at a specific time 

### ISSUE THREAD

**Issue by cg-cnu** [cg-cnu/vscode-remind-me#3]
Suggested by @KobayashiRo at https://github.com/cg-cnu/vscode-remind-me/issues/1#issuecomment-336186981

> may be you can add keyword like at .
e.g watch tv at 22:00
and it will remind me at 22:00

**Comment by KobayashiRo** [comment]
I 'm fork the code and add the specific time remind..
 hahaha....
 just only check the last word  indexof :

**Comment by cg-cnu** [comment]
That's wonderful!  👏 
Just a small suggestion. Let's use `@10a` or `@10p` as the convention rather than `:`. I feel its more natural 🙂  So, if the syntax is `meeting @4p` - set the reminder for 4pm. If `meeting 4` - set the reminder for 4 mins from now
Let me know what you think 😄

**Comment by KobayashiRo** [comment]
er...  if i wanna remind me at  10:30  so  ... it's @10a30 ?

**Comment by cg-cnu** [comment]
Alright this might become confusing real soon.... what you said make sense. I don't want to make this tedious for people, it should be a quick and easy to remember. Lets try to balance the features and a simple syntax to remember.

To register a reminder from now... 
4.5h -> Remind me four and half hours from now
10m -> Remind 10 minutes from now

Only support hours and minutes ?

To register a reminder at a specific time...
4:30p -> Remind at 4.30 pm
11:45a -> Remind at 11.45 am

Only support 12 hour clock with am and pm ?

**Comment by cg-cnu** [comment]
Hey @KobayashiRo are you still interested in working on this ?

**Comment by EvgeniyMakhmudov** [comment]
The full useful of this extension will bw when i can quickly say to vscode remind me do something in HH:MM o'clock.
So i'm want this feature, even right now :)

**Comment by cg-cnu** [comment]
Hey guys! Sorry for delay but the latest version of the extension is a complete rewrite which uses [sherlockjs](https://github.com/neilgupta/Sherlock) for even parsing. Now you can use natural language to event reminders. Let me know if you got any feedback!

**Comment by EvgeniyMakhmudov** [comment]
There is bug. Right now local time is morning 10:53. I enter value "test at 10:59" and get response "test in 12 hours". Than I enter "test at 11:00" and get response "test in 6 minutes". Only last behavior is correct. 
I play some another values to understand that is a really error.

**Comment by cg-cnu** [comment]
Hey @EvgeniyMakhmudov I did checked it, looks like if you are not provide am or pm its getting confused based on the local time. This is an issue with the upstream sherlockjs module. I will talk to them and get it clarified. Thanks for your inputs!

**Comment by EvgeniyMakhmudov** [comment]
Needed to understand that not all counties in a world used  AM/PM notation. For example i am from Russia ans we used 24 hours clock format. 
It's will be good that can be possible used 24 hours. Even if will be needed setting for this.

**Comment by cg-cnu** [comment]
Sure @EvgeniyMakhmudov That's a valid point! I am talking to the sherlock developer, will update once I have input from him. Thanks for your ideas and inputs! 😃

**Comment by cg-cnu** [comment]
Hi @EvgeniyMakhmudov Sorry for no reply. I did couple of tests and its working as expected even with the 24 hours notation and AM/PM. Here are the samples..

current time is 05:30 pm

- test at 5:35 > 'test' in 5 minutes
- test at 17:35 >  'test' in 5 minutes
- test at 22:15 > 'test' in about 5 hours

I am going to write some test cases for these. Thanks! Let me know if you are still having trouble with this.

**Comment by EvgeniyMakhmudov** [comment]
Hello, i try to test it. And everything looks as worked.
